version: '3'
services:
  api:
    build: .
    env_file: 
      - .env
    depends_on:
      - postgres
    ports:
      - '9002:9002'

  postgres:
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data:
