version: '3'
services:
  api:
    build: .
    env_file: 
      - .env
    depends_on:
      - mysql
    ports:
      - '9002:9002'
  mysql:
    image: 'mysql:8'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql

volumes:
  db-data:
