log:
  level:
    console: verbose
    file: verbose
    query: error

link:
  reset-password: https://www.manumura.com/reset-password?token=
  verify-email: https://www.manumura.com/verify-email?token=
